; ---------------------------------------------------------------------------
; Special Stage mappings and VRAM pointers
; ---------------------------------------------------------------------------

SS_MapIndex:

		; wall
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 01 (normal blue wall)
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 02 (blue/green wall 1)
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 03 (blue/green wall 2)
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 04 (blue/green wall 3)
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 05 (blue/green wall 4)
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 06 (blue/green wall 5)
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 07 (blue/green wall 6)
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 08 (blue/green wall 7)
		specialStageData	0, Map_SSWalls, 0, ArtTile_SS_Wall				; 09 (blue/green wall 8)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 0A (normal yellow wall)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 0B (yellow/blue wall 1)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 0C (yellow/blue wall 2)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 0D (yellow/blue wall 3)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 0E (yellow/blue wall 4)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 0F (yellow/blue wall 5)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 10 (yellow/blue wall 6)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 11 (yellow/blue wall 7)
		specialStageData	0, Map_SSWalls, 1, ArtTile_SS_Wall				; 12 (yellow/blue wall 8)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 13 (normal purple wall)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 14 (purple/yellow wall 1)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 15 (purple/yellow wall 2)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 16 (purple/yellow wall 3)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 17 (purple/yellow wall 4)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 18 (purple/yellow wall 5)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 19 (purple/yellow wall 6)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 1A (purple/yellow wall 7)
		specialStageData	0, Map_SSWalls, 2, ArtTile_SS_Wall				; 1B (purple/yellow wall 8)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 1C (normal green wall)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 1D (green/purple wall 1)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 1E (green/purple wall 2)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 1F (green/purple wall 3)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 20 (green/purple wall 4)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 21 (green/purple wall 5)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 22 (green/purple wall 6)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 23 (green/purple wall 7)
		specialStageData	0, Map_SSWalls, 3, ArtTile_SS_Wall				; 24 (green/purple wall 8)

		; stage objects
		specialStageData	0, Map_Bump,0, ArtTile_SS_Bumper				; 25 (stage object)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_W_Block				; 26 (unused)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_Goal					; 27 (stage object)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_Extra_Life				; 28 (unused)
		specialStageData	0, Map_SS_Up, 0, ArtTile_SS_Up_Down				; 29 (stage object)
		specialStageData	0, Map_SS_Down, 0, ArtTile_SS_Up_Down				; 2A (stage object)
		specialStageData	0, Map_SS_R,1, ArtTile_SS_R_Block				; 2B (stage object)
		specialStageData	0, Map_SS_Glass,0, ArtTile_SS_Red_White_Block			; 2C (stage object)
		specialStageData	0, Map_SS_Glass,0, ArtTile_SS_Glass				; 2D (stage object)
		specialStageData	0, Map_SS_Glass,3, ArtTile_SS_Glass				; 2E (stage object)
		specialStageData	0, Map_SS_Glass,1, ArtTile_SS_Glass				; 2F (stage object)
		specialStageData	0, Map_SS_Glass,2, ArtTile_SS_Glass				; 30 (stage object)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_R_Block				; 31 (anim)
		specialStageData	1, Map_Bump,0, ArtTile_SS_Bumper				; 32 (anim)
		specialStageData	2, Map_Bump,0, ArtTile_SS_Bumper				; 33 (anim)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_Zone_1				; 34 (unused)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_Zone_2				; 35 (unused)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_Zone_3				; 36 (unused)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_Zone_4				; 37 (unused)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_Zone_5				; 38 (unused)
		specialStageData	0, Map_SS_R,0, ArtTile_SS_Zone_6				; 39 (unused)
		specialStageData	0, Map_Ring,1, ArtTile_SS_Ring					; 3A (stage object)

		; emeralds
		specialStageData	0, Map_SS_Chaos, 0, ArtTile_SS_Emerald				; 3B (1)
		specialStageData	0, Map_SS_Chaos, 0, ArtTile_SS_Emerald				; 3C (2)
		specialStageData	0, Map_SS_Chaos, 0, ArtTile_SS_Emerald				; 3D (3)
		specialStageData	0, Map_SS_Chaos, 0, ArtTile_SS_Emerald				; 3E (4)
		specialStageData	0, Map_SS_Chaos, 0, ArtTile_SS_Emerald				; 3F (5)
		specialStageData	0, Map_SS_Chaos, 0, ArtTile_SS_Emerald				; 40 (6)

		specialStageData	0, Map_SS_R,0, ArtTile_SS_Ghost_Block				; 41 (stage object)
		specialStageData	1, Map_Ring,1, ArtTile_SS_Ring					; 42 (anim)
		specialStageData	2, Map_Ring,1, ArtTile_SS_Ring					; 43 (anim)
		specialStageData	3, Map_Ring,1, ArtTile_SS_Ring					; 44 (anim)
		specialStageData	4, Map_Ring,1, ArtTile_SS_Ring					; 45 (anim)
		specialStageData	0, Map_SS_Glass,1, ArtTile_SS_Emerald_Sparkle			; 46 (anim)
		specialStageData	1, Map_SS_Glass,1, ArtTile_SS_Emerald_Sparkle			; 47 (anim)
		specialStageData	2, Map_SS_Glass,1, ArtTile_SS_Emerald_Sparkle			; 48 (anim)
		specialStageData	3, Map_SS_Glass,1, ArtTile_SS_Emerald_Sparkle			; 49 (anim)
		specialStageData	2, Map_SS_R,0, ArtTile_SS_Ghost_Block				; 4A (stage object)
		specialStageData	0, Map_SS_Glass,0, ArtTile_SS_Glass				; 4B (anim)
		specialStageData	0, Map_SS_Glass,3, ArtTile_SS_Glass				; 4C (anim)
		specialStageData	0, Map_SS_Glass,1, ArtTile_SS_Glass				; 4D (anim)
		specialStageData	0, Map_SS_Glass,2, ArtTile_SS_Glass				; 4E (anim)

		; extra
		specialStageData	0, Map_SS_Chaos, 0, ArtTile_SS_Emerald				; 4F (7)
SS_MapIndex_end
