# Code generated by LLaMA

with open('main.bin', 'rb') as f_in, open('output.bin', 'wb') as f_out:
    while True:
        byte1 = f_in.read(1)
        byte2 = f_in.read(1)
        if not byte1 or not byte2:
            break
        f_out.write(byte2)
        f_out.write(byte1)