# Code generated by ChatGPT

import glob

files = glob.glob('*.bin')

for file_path in files:
    with open(file_path, 'rb') as infile:
        data = infile.read()

    output = bytearray()

    for byte in data:
        half_byte1 = byte >> 4
        half_byte2 = byte & 0x0F

        duplicated_byte1 = half_byte1 << 4 | half_byte1
        duplicated_byte2 = half_byte2 << 4 | half_byte2

        output.append(duplicated_byte1)
        output.append(duplicated_byte2)

    duplicated_data = bytes(output)

    output_file_path = file_path.split(".")[0] + "_output.bin"

    with open(output_file_path, 'wb') as outfile:
        outfile.write(duplicated_data)