# Code generated by ChatGPT

import os
import glob

files = glob.glob('*.bin')

for file_path in files:
    with open(file_path, 'rb') as infile:
        data = infile.read()

    output = bytearray()

    for i in range(0, len(data), 2):
        byte1 = data[i] >> 4
        byte2 = data[i+1] >> 4

        merged_byte = (byte1 << 4) | byte2

        output.append(merged_byte)

    shrunk_data = bytes(output)

    output_file_name = os.path.splitext(file_path)[0] + '_output.bin'

    with open(output_file_name, 'wb') as outfile:
        outfile.write(shrunk_data)