# Code generated by ChatGPT

import glob

bmp_files = glob.glob("*.bmp")

for bmp_file in bmp_files:
    with open(bmp_file, "rb") as file:
        data = file.read()

    data = data[0x76:]

    output_file = bmp_file.replace(".bmp", "_output.bin")
    with open(output_file, "wb") as file:
        file.write(data)